Amplicode/amplicode-frontend

packages/codegen/src/building-blocks/stages/writing/pieces/mvp/addAddonPalette.ts, packages/codegen/src/generators/react-typescript/addon/template-model.ts, packages/codegen/src/generators/react-typescript/addon/write.ts, test-addon/amplicode.addon-metadata.json, test-addon/package-lock.json, test-addon/package.json, test-addon/palette.tsx
=> feat: support addon's palette injection to main palette #58

package.json, packages/codegen/src/building-blocks/pipelines/amplicodePipeline.ts, packages/codegen/src/building-blocks/stages/graphql-schema/amplicodeGetGraphQLSchema.ts, packages/codegen/src/building-blocks/stages/template-model/amplicodeDeriveTemplateModel.ts, packages/codegen/src/generators/react-typescript/app/template-model.ts, packages/codegen/src/generators/react-typescript/app/template/package.json, packages/codegen/src/generators/react-typescript/entity-list/template-model.ts, scripts/schema.graphql
=> fix: types generation fails due to incorrect schema path #76

example-app/package-lock.json, example-app/src/index.tsx, packages/codegen/src/generators/react-typescript/app/template/src/index.tsx
=> fix: addon i18n doesn't work when using components from addon #110

example-app/package-lock.json, packages/react-core/src/screen-api/Screens.ts
affects: @amplicode/react-core
=> fix: breadcrumbs can grow and grow by adding new ones #101

packages/codegen/src/common/studio/studio-model.ts, packages/codegen/src/generators/react-typescript/entity-details/answers.ts, packages/codegen/src/generators/react-typescript/entity-list/answers.ts, packages/codegen/src/generators/react-typescript/entity-management/answers.ts
=> chore: add default values for add to menu parameter #94

packages/codegen/src/generators/react-typescript/app/template/src/app/login/Login.tsx.ejs
=> fix: dynamic caption on login screen #91

example-app/package-lock.json, example-app/src/dev/palette.tsx, packages/codegen/src/generators/react-typescript/app/template/src/dev/palette.tsx
more variants for components in Data display, Navigation and Feedback categories
=> feat: enrich antd palette #117

example-app/src/app/owner/OwnerList.tsx, example-app/src/app/pet/PetList.tsx, example-app/src/app/read-only-owner/ReadOnlyOwnerList.tsx, packages/codegen/src/generators/react-typescript/entity-list/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs
=> fix: error when refreshing editor page #102

example-app/src/app/screens/owner/OwnerList.tsx, example-app/src/app/screens/pet/PetList.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerList.tsx, packages/codegen/src/generators/react-typescript/entity-list/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-management/template/Cards.tsx.ejs
=> fix: invalid request when editor page is refreshed #102

example-app/src/core/security/security-store.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/security/security-store.ts
=> chore: adding TSDoc notes for securityStore #146

packages/codegen/src/building-blocks/stages/graphql-schema/amplicodeGetGraphQLSchema.ts
=> chore: new default graphql schema location #144

example-app/src/app/App.test.tsx, example-app/src/app/screens/owner/OwnerList.tsx, example-app/src/app/screens/pet/PetList.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerList.tsx, example-app/src/index.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/App.test.tsx, packages/codegen/src/generators/react-typescript/app/template/src/index.tsx, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs
=> chore: editing apollo client config #132

packages/codegen/src/generators/react-typescript/entity-list/template-model.ts, packages/codegen/src/generators/react-typescript/entity-management/write.ts, packages/codegen/src/test/generators/react-typrscript/entity-details/entity-details.test.ts
=> test: fix TeamCity build

example-app/src/dev/previews.tsx, packages/codegen/src/building-blocks/stages/writing/pieces/mvp/mvp.ts, packages/codegen/src/generators/react-typescript/app/template/src/dev/previews.tsx
=> feat: add generated screens to preview #98

packages/codegen/src/building-blocks/stages/answers/amplicode/ScreenAnswers.ts, packages/codegen/src/building-blocks/stages/template-model/pieces/amplicode/ScreenTemplateModel.ts, packages/codegen/src/common/studio/studio-model.ts, packages/codegen/src/generators/react-typescript/entity-list/answers.ts, packages/codegen/src/generators/react-typescript/entity-list/template-model.ts, packages/codegen/src/generators/react-typescript/entity-management/answers.ts, packages/codegen/src/generators/react-typescript/entity-management/template-model.ts, packages/codegen/src/test/generators/react-typrscript/entity-details/entity-details.test.ts, scripts/generate-owner-list-readonly.js, scripts/generate-owner-list-standalone.js, scripts/generate-owner-management.js, scripts/generate-pet-crud.js
=> feat: add route as a separate screen template parameter #178

example-app/package-lock.json, example-app/src/app/screens/owner/OwnerEditor.tsx, example-app/src/app/screens/pet/PetEditor.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerDetails.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerList.tsx, example-app/src/core/crud/useOpenItemScreen.ts, example-app/src/core/crud/useSubmit.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/crud/useOpenItemScreen.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/crud/useSubmit.ts, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-details/template/EntityDetails.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-details/template/EntityEditor.tsx.ejs
=> chore: minor ejs template improvements

example-app/src/app/menu/Menu.tsx, example-app/src/app/screens/owner/OwnerCards.tsx, example-app/src/app/screens/owner/OwnerCardsEditor.tsx, example-app/src/app/screens/owner/OwnerListEditor.tsx, example-app/src/app/screens/pet/PetCards.tsx, example-app/src/app/screens/pet/PetCardsEditor.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerCards.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerCardsDetails.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx, example-app/src/core/i18n/en.json, example-app/src/core/screen-api/screen-registry.ts, example-app/src/dev/previews.tsx, example-app/src/gql/graphql.ts, example-app/src/gql/index.ts, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-list/answers.ts, packages/codegen/src/generators/react-typescript/entity-list/template-model.ts, packages/codegen/src/generators/react-typescript/entity-list/write.ts, packages/codegen/src/generators/react-typescript/entity-management/answers.ts, packages/codegen/src/generators/react-typescript/entity-management/template-model.ts, packages/codegen/src/test/generators/react-typrscript/entity-list/entity-list.test.ts, scripts/bootstrap-react-app.js, scripts/generate-owner-cards-readonly.js, scripts/generate-owner-cards-standalone.js, scripts/generate-owner-management-cards.js, scripts/generate-owner-management-list.js, scripts/generate-pet-management-cards.js
=> feat: add entity list type "list" #142

CONTRIBUTING.md, example-app/src/app/App.css, example-app/src/app/screens/owner/OwnerCards.tsx, example-app/src/app/screens/owner/OwnerList.tsx, example-app/src/app/screens/pet/PetCards.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx, example-app/src/gql/graphql.ts, example-app/src/gql/index.ts, packages/codegen/src/generators/react-typescript/app/template/src/app/App.css, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-list/write.ts, packages/codegen/src/test/generators/react-typrscript/entity-details/entity-details.test.ts, packages/codegen/src/test/generators/react-typrscript/entity-list/entity-list.test.ts, packages/codegen/src/test/test-commons.ts, scripts/generate-owner-cards-standalone.js, scripts/generate-owner-management-cards.js, scripts/generate-owner-management-list.js, scripts/generate-pet-management-cards.js
=> chore: crud screen improvements

example-app/package-lock.json, example-app/package.json, packages/codegen/src/generators/react-typescript/app/template/package-lock.json, packages/codegen/src/generators/react-typescript/app/template/package.json
=> chore: update @apollo/client version #90

example-app/package-lock.json, example-app/src/app/screens/owner/OwnerCards.tsx, example-app/src/app/screens/pet/PetCards.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx, packages/codegen/src/generators/react-typescript/app/template/package-lock.json
=> fix: can't install npm packages after generating app template #226

example-app/src/app/screens/owner/OwnerCards.tsx, example-app/src/app/screens/owner/OwnerCardsEditor.tsx, example-app/src/app/screens/owner/OwnerList.tsx, example-app/src/app/screens/owner/OwnerListEditor.tsx, example-app/src/app/screens/pet/PetCards.tsx, example-app/src/app/screens/pet/PetCardsEditor.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerCards.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerCardsDetails.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-details/template/EntityDetails.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-details/template/EntityEditor.tsx.ejs, scripts/generate-management/owner-management-cards.js, scripts/generate-management/owner-management-list.js, scripts/generate-management/pet-management-cards.js, scripts/generate-readonly/owner-cards-readonly.js, scripts/generate-standalone/owner-cards-standalone.js
=> chore: remove /* GraphQL */ from screen templates #165

example-app/src/app/screens/owner/OwnerTable.tsx, example-app/src/app/screens/owner/OwnerTableEditor.tsx, example-app/src/app/screens/pet/PetList.tsx, example-app/src/app/screens/pet/PetListEditor.tsx, example-app/src/app/screens/pet/PetTable.tsx, example-app/src/app/screens/pet/PetTableEditor.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerList.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerListDetails.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerTable.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerTableDetails.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerList.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerTable.tsx, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs, scripts/generate-management/owner-management-table.js, scripts/generate-management/pet-management-list.js, scripts/generate-management/pet-management-table.js, scripts/generate-readonly/owner-list-readonly.js, scripts/generate-readonly/owner-table-readonly.js, scripts/generate-standalone/owner-list-standalone.js, scripts/generate-standalone/owner-table-standalone.js
=> chore: applying the GraphQL changes to the new generator structure

example-app/src/app/App.css, example-app/src/app/screens/owner/OwnerTable.tsx, example-app/src/app/screens/pet/PetTable.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerTable.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerTable.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/App.css, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs, packages/codegen/src/test/generators/react-typrscript/entity-list/standalone-table.test.ts, packages/codegen/src/test/generators/react-typrscript/entity-management/readonly-table.test.ts
=> refactor: get rid of inline styles in table screens #219

packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs
=> fix: read only list should not have action buttons #207

example-app/src/core/crud/useOpenItemScreen.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/crud/useOpenItemScreen.ts
=> fix: error when refreshing page with editor in "new entity" state #102

packages/react-antd/src/components/entity-lookup-field/EntityLookupField.css, packages/react-antd/src/components/entity-lookup-field/EntityLookupField.tsx
affects: @amplicode/react-antd
=> feat: add clear button in entity lookup field

example-app/src/app/App.test.tsx, example-app/src/app/App.tsx, example-app/src/app/header/Header.tsx, example-app/src/app/login/Login.tsx, example-app/src/core/error/ServerErrorInterceptor.tsx, example-app/src/core/security/security-context.ts, example-app/src/core/security/security-store.ts, example-app/src/core/security/security.ts, example-app/src/dev/useInitial.ts, example-app/src/index.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/App.test.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/App.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/header/Header.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/login/Login.tsx.ejs, packages/codegen/src/generators/react-typescript/app/template/src/core/error/ServerErrorInterceptor.tsx, packages/codegen/src/generators/react-typescript/app/template/src/core/security/security-context.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/security/security-store.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/security/security.ts, packages/codegen/src/generators/react-typescript/app/template/src/dev/useInitial.ts, packages/codegen/src/generators/react-typescript/app/template/src/index.tsx
=> feat: automatic relogin on session #228

example-app/src/app/App.css, example-app/src/app/screens/owner/OwnerTable.tsx, example-app/src/app/screens/pet/PetTable.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerTable.tsx, example-app/src/app/screens/read-only-pet/ReadOnlyPetTable.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerTable.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/App.css, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs, packages/codegen/src/test/generators/react-typrscript/entity-list/standalone-table.test.ts
=> chore: table screen improvements (part 1) #295

example-app/src/app/screens/owner/OwnerTable.tsx, example-app/src/app/screens/pet/PetTable.tsx, example-app/src/app/screens/read-only-owner/ReadOnlyOwnerTable.tsx, example-app/src/app/screens/read-only-pet/ReadOnlyPetTable.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerTable.tsx, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs, packages/codegen/src/test/generators/react-typrscript/entity-list/standalone-table.test.ts
=> feat: ability to deselect row in table screen #295

packages/eslint-config-amplicode-react/.eslintrc.json, packages/react-antd/src/components/date/TimePicker.tsx, packages/react-antd/src/components/hotkeys/HotkeyInfo.tsx, packages/react-core/src/i18n/I18nStore.tsx, packages/react-core/src/menu/MenuStore.ts, packages/react-core/src/screen-api/ReactComponent.ts, packages/react-core/src/screen-api/ScreenStore.ts, packages/react-core/src/screen-api/Screens.ts, packages/react-core/src/test/util/filterFieldValues.test.tsx, packages/react-core/src/util/EventEmitter.ts, packages/react-core/src/util/filterFieldValues.ts
affects: eslint-config-amplicode-react, @amplicode/react-core
=> chore: more sctrict eslint rules in packages

packages/react-core/src/i18n/I18nStore.tsx
affects: @amplicode/react-core
=> fix: locale resets to English when page is reloaded #309

packages/codegen/src/building-blocks/includes/AmplicodeFormField.ejs, packages/codegen/src/test/generators/react-typrscript/entity-details/entity-details.test.ts
=> chore: set default value for checkbox form control

example-app/src/app/screens/scalars/TestScalarsCards.tsx, example-app/src/app/screens/scalars/TestScalarsCardsEditor.tsx, example-app/src/core/schema/typeDefs.ts, example-app/src/core/transform/model/LocalDateTime/deserializeLocalDateTime.ts, example-app/src/core/transform/model/LocalDateTime/serializeLocalDateTime.ts, example-app/src/core/transform/model/custom-scalars.ts, example-app/src/gql/gql.ts, example-app/src/gql/graphql.ts, packages/codegen/src/building-blocks/includes/AmplicodeFormField.ejs, packages/codegen/src/test/fixtures/schema/schema.graphql, scripts/bootstrap-app/queries.js, scripts/schema.graphql
=> feat: custom scalars - BigInteger, Long, BigDecimal #230

example-app/src/core/i18n/messages/ru.json, packages/codegen/src/generators/react-typescript/app/template/src/core/i18n/messages/ru.json
=> fix: incorrect caption on read-only details screen #314

example-app/src/app/App.css, example-app/src/core/crud/ErrorMessage.tsx, packages/codegen/src/generators/react-typescript/app/template/src/app/App.css, packages/codegen/src/generators/react-typescript/app/template/src/core/crud/ErrorMessage.tsx
=> fix: form validation message doesn't have a bottom margin #348

example-app/src/app/screens/owner/OwnerCards.tsx, example-app/src/app/screens/owner/OwnerCardsWithFilter.tsx, example-app/src/app/screens/owner/OwnerList.tsx, example-app/src/app/screens/owner/OwnerTable.tsx, example-app/src/app/screens/pet/PetCards.tsx, example-app/src/app/screens/pet/PetList.tsx, example-app/src/app/screens/pet/PetTable.tsx, example-app/src/app/screens/scalars/TestScalarsCards.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerCards.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerList.tsx, example-app/src/app/screens/standalone-list/StandaloneOwnerTable.tsx, example-app/src/core/i18n/messages/ru.json, packages/codegen/src/generators/react-typescript/app/template/src/core/i18n/messages/ru.json, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs
=> feat: track 'loading' and 'error' statuses of mutations #128

example-app/package-lock.json, example-app/src/app/screens/pet/PetCardsEditor.tsx, example-app/src/app/screens/pet/PetListEditor.tsx, example-app/src/app/screens/pet/PetTableEditor.tsx, example-app/src/app/screens/scalars/TestScalarsCardsEditor.tsx, example-app/src/core/i18n/providers/AntdConfigProvider.tsx, example-app/src/core/i18n/providers/DayjsProvider.tsx, example-app/src/core/i18n/providers/I18nProvider.tsx, packages/codegen/src/generators/react-typescript/app/template/src/core/i18n/providers/AntdConfigProvider.tsx, packages/codegen/src/generators/react-typescript/app/template/src/core/i18n/providers/DayjsProvider.tsx, packages/codegen/src/generators/react-typescript/app/template/src/core/i18n/providers/I18nProvider.tsx, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs, packages/codegen/src/generators/react-typescript/entity-details/template-model.ts, packages/codegen/src/generators/react-typescript/entity-details/template/EntityEditor.tsx.ejs, packages/react-antd/package.json, packages/react-core/src/i18n/I18nStore.tsx
affects: @amplicode/codegen, @amplicode/react-antd
=> fix: components using dayjs are not updated when changing locale #322

example-app/package-lock.json, example-app/src/app/menu/Menu.tsx, packages/codegen/src/building-blocks/stages/writing/pieces/mvp/addMvpAppMenu.ts
=> fix: missing i18n messages

example-app/package.json, example-app/vite.config.ts, packages/codegen/src/generators/react-typescript/app/answers.ts, packages/codegen/src/generators/react-typescript/app/template-model.ts, packages/codegen/src/generators/react-typescript/app/template/package.json, packages/codegen/src/generators/react-typescript/app/template/vite.config.ts
=> chore: improve dev server proxy configuration #338

example-app/src/app/screens/management/OwnerCards.tsx, example-app/src/app/screens/management/OwnerCardsWithFilter.tsx, example-app/src/app/screens/management/OwnerList.tsx, example-app/src/app/screens/management/PetCards.tsx, example-app/src/app/screens/management/PetDiseaseCards.tsx, example-app/src/app/screens/management/PetDiseaseList.tsx, example-app/src/app/screens/management/PetList.tsx, example-app/src/app/screens/management/TestNotNullScalarsCards.tsx, example-app/src/app/screens/management/TestScalarsCards.tsx, example-app/src/app/screens/standalone-collection/StandaloneOwnerCards.tsx, example-app/src/app/screens/standalone-collection/StandaloneOwnerList.tsx, example-app/src/app/screens/standalone-collection/StandalonePetDiseaseList.tsx, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/src/generators/react-typescript/common/template/List.tsx.ejs
=> fix: modal does not close until the deletion is finished #417

example-app/src/app/menu/Menu.tsx, example-app/src/app/routes/AppRoutes.tsx, example-app/src/app/screens/lookup/PetDescriptionLookupCards.tsx, example-app/src/app/screens/management/PetCards.tsx, example-app/src/app/screens/management/PetCardsEditor.tsx, example-app/src/app/screens/management/PetList.tsx, example-app/src/app/screens/management/PetListEditor.tsx, example-app/src/app/screens/management/PetTable.tsx, example-app/src/app/screens/management/PetTableEditor.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetCards.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetCardsDetails.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetList.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetListDetails.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetTable.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetTableDetails.tsx, example-app/src/app/screens/standalone-details/StandalonePetDetails.tsx, example-app/src/core/display-name/getPetDescriptionDTODisplayName.ts, example-app/src/core/i18n/messages/en.json, example-app/src/dev/previews.tsx, example-app/src/gql/gql.ts, example-app/src/gql/graphql.ts, scripts/bootstrap-app/generate-lookup/pet-description-lookup-cards.js, scripts/bootstrap-app/queries.js, scripts/bootstrap-react-app.js
=> feat: support IDs with name other than "id" #242

example-app/src/app/screens/management/OwnerTable.tsx, example-app/src/app/screens/management/PetDiseaseTable.tsx, example-app/src/app/screens/management/PetTable.tsx, example-app/src/app/screens/management/TestScalarsTable.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyOwnerTable.tsx, example-app/src/app/screens/readonly-collection/ReadOnlyPetTable.tsx, example-app/src/app/screens/standalone-collection/StandaloneOwnerTable.tsx, packages/codegen/src/generators/react-typescript/common/template/Table.tsx.ejs, packages/codegen/src/test/generators/react-typrscript/entity-list/standalone-table.test.ts
=> fix: table looks ugly when too many columns #423

CONTRIBUTING.md, packages/codegen/src/building-blocks/stages/graphql-schema/amplicodeGetGraphQLSchema.ts, packages/codegen/src/building-blocks/stages/options/pieces/amplicode.ts, packages/codegen/src/common/cli-options.ts, packages/codegen/src/test/building-blocks/stages/graphql-schema/amplicodeGetGraphQLSchema.test.ts, packages/codegen/src/test/common/cli-options.test.ts
=> test: 'update-schema' generator tests and docs

example-app/src/core/crud/entity-lookup-field/EntityLookupField.tsx, packages/codegen/src/generators/react-typescript/app/template/src/core/crud/entity-lookup-field/EntityLookupField.tsx
=> chore: allow using disabled prop on EntityLookupField #439

example-app/src/app/screens/management/PetCardsEditor.tsx, example-app/src/app/screens/management/PetListEditor.tsx, example-app/src/app/screens/management/PetTableEditor.tsx, example-app/src/core/crud/entity-lookup-field/EntityLookupField.tsx, packages/codegen/src/building-blocks/includes/AmplicodeFormField.ejs, packages/codegen/src/generators/react-typescript/app/template/src/core/crud/entity-lookup-field/EntityLookupField.tsx
=> chore: rename EntityLookupFieldProps prop label to drawerTitle #438

example-app/package-lock.json, example-app/src/app/menu/Menu.tsx, example-app/src/app/routes/AppRoutes.tsx, example-app/src/app/screens/management/PetCards.tsx, example-app/src/app/screens/management/VisitWithFilter.tsx, example-app/src/app/screens/management/VisitWithFilterEditor.tsx, example-app/src/app/screens/management/VisitWithFilterScreenLayout.tsx, example-app/src/core/display-name/getVisitDTODisplayName.ts, example-app/src/core/i18n/messages/en.json, example-app/src/core/transform/model/serializeVariables.ts, example-app/src/core/transform/types.ts, example-app/src/core/transform/util.ts, example-app/src/dev/previews.tsx, example-app/src/gql/gql.ts, example-app/src/gql/graphql.ts, packages/codegen/src/building-blocks/includes/AmplicodeFormField.ejs, packages/codegen/src/generators/react-typescript/app/template/src/core/transform/model/serializeVariables.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/transform/types.ts, packages/codegen/src/generators/react-typescript/app/template/src/core/transform/util.ts, packages/codegen/src/generators/react-typescript/common/template/Cards.tsx.ejs, packages/codegen/test/integration/entity-list/filter-in-standalone-cards.test.ts, scripts/bootstrap-app/generate-management/visit-with-filter.js, scripts/bootstrap-react-app.js
=> fix: add example with hidden filters

example-app/vite.config.ts, packages/codegen/src/building-blocks/stages/writing/pieces/replace/ReplacementTargetNotFoundError.ts, packages/codegen/src/building-blocks/stages/writing/pieces/replace/replaceEnvVarValue.test.ts, packages/codegen/src/building-blocks/stages/writing/pieces/replace/replaceEnvVarValue.ts, packages/codegen/src/building-blocks/stages/writing/pieces/replace/replaceStringValue.test.ts, packages/codegen/src/building-blocks/stages/writing/pieces/replace/replaceStringValue.ts, packages/codegen/src/building-blocks/stages/writing/pieces/writeTemplate.ts, packages/codegen/src/generators/react-typescript/app/template/vite.config.ts, packages/codegen/src/generators/react-typescript/auth-oauth2-keycloak-stateful/index.ts, packages/codegen/src/generators/react-typescript/auth-oauth2-keycloak-stateful/template/Login.tsx, packages/codegen/src/generators/react-typescript/auth-oauth2-keycloak-stateful/template/security.ts, packages/codegen/src/generators/react-typescript/auth-oauth2-keycloak-stateful/write.ts, packages/codegen/src/test/init.test.ts
=> feat: support OAuth2.0 using Keycloak with backend as client #419

example-app/vite.config.ts, packages/codegen/src/generators/react-typescript/app/template/vite.config.ts, packages/codegen/test/integration/app/app.test.ts
=> feat: allow setting BASE_URL with environment variable#497

CONTRIBUTING.md, packages/codegen/.mocharc.yml, packages/codegen/src/common/cli/cli.ts, packages/codegen/src/generators/react-typescript/app/index.ts, packages/codegen/src/generators/react-typescript/auth-oauth2-keycloak-stateful/index.ts, packages/codegen/src/generators/react-typescript/update-schema/index.ts, packages/codegen/src/init.ts, packages/codegen/test/e2e/cli/list.test.js
=> feat: add criteria for component generator #479
